import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { api, loadBook, loadBooks, loadCategories } from './api.js';
import './styles.css';
import './admin.css';
import { MyLibrary, Reservations, Fines } from './Circulation.jsx';
import { AuthProvider, ProtectedRoute, LoginPage, RegisterPage, ProfilePage, useAuth } from './Auth.jsx';

function Header() {
  const [query, setQuery] = React.useState(''); const navigate = useNavigate(); const { user, logout } = useAuth();
  return <header className="topbar"><Link className="brand" to="/books"><span className="brand-mark">L</span><span>Libra<span className="brand-light">Mind</span><small>UNIVERSITY LIBRARY</small></span></Link><form className="header-search" onSubmit={e => { e.preventDefault(); navigate(`/books?search=${encodeURIComponent(query)}`); }}><span>⌕</span><input aria-label="Search books" placeholder="Search books, authors, topics…" value={query} onChange={e => setQuery(e.target.value)}/><kbd>⌘ K</kbd></form><nav><Link to="/books">Catalogue</Link>{user && <><Link to="/my-library">My library</Link><Link to="/reservations">Reservations</Link><Link to="/fines">Fines</Link>{user.role === 'ADMIN' && <Link to="/admin/books">Manage books</Link>}<Link to="/profile" className="profile-nav">{user.name}</Link><button className="avatar" onClick={async () => { await logout(); navigate('/login'); }} title="Sign out">↪</button></>}{!user && <Link to="/login">Sign in</Link>}</nav></header>;
}function Status({ available }) { return <span className={`status ${available ? 'in-stock' : 'out-stock'}`}><i/>{available ? 'Available' : 'Unavailable'}</span>; }
function BookCard({ book }) { return <Link className="book-card" to={`/books/${book._id}`}><div className="cover-wrap">{book.coverImage ? <img src={book.coverImage} alt=""/> : <div className="cover-placeholder"><span>LIBRARY<br/>EDITION</span><strong>{book.title}</strong><small>{book.authors?.[0]}</small></div>}<span className="cover-overlay">View details ↗</span></div><div className="book-meta"><span className="eyebrow">{book.category}</span><h3>{book.title}</h3><p>{book.authors?.join(', ')}</p><Status available={book.availableCopies > 0}/></div></Link>; }
function State({ children, kind='loading' }) { return <div className={`state ${kind}`}>{kind === 'loading' && <span className="spinner"/>}<div>{children}</div></div>; }
function Catalogue() {
  const [params, setParams] = useSearchParams(); const search = params.get('search') || ''; const category = params.get('category') || ''; const sort = params.get('sort') || 'title';
  const [categories, setCategories] = React.useState([]); const [result, setResult] = React.useState(null); const [error, setError] = React.useState('');
  React.useEffect(() => { let live = true; loadCategories().then(v => live && setCategories(v)).catch(() => {}); return () => { live=false; }; }, []);
  React.useEffect(() => { let live = true; setError(''); setResult(null); loadBooks({ search, category, sort, page: 1, limit: 24 }).then(v => live && setResult(v)).catch(e => live && setError(e.response?.data?.message || 'Could not load the catalogue. Sign in and try again.')); return () => { live=false; }; }, [search, category, sort]);
  const set = (key, value) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); setParams(next); };
  return <main className="page"><div className="breadcrumb">DISCOVER <span>/</span> CATALOGUE</div><section className="hero"><div><div className="eyebrow">THE UNIVERSITY COLLECTION</div><h1>Ideas begin<br/><em>between pages.</em></h1><p>Explore a growing collection of knowledge, research, and inspiration.</p></div><div className="hero-art"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="hero-book">L</div><span className="art-caption">EST. FOR<br/>THE CURIOUS</span></div></section>
  <div className="catalogue-heading"><div><div className="eyebrow">FIND YOUR NEXT READ</div><h2>{search ? `Results for “${search}”` : 'Explore the catalogue'}</h2><p>{result ? `${result.pagination.total} titles in the collection` : 'Browse by subject or find a specific title.'}</p></div><div className="selects"><select value={category} onChange={e => set('category', e.target.value)} aria-label="Filter by category"><option value="">All categories</option>{categories.map(c => <option key={c}>{c}</option>)}</select><select value={sort} onChange={e => set('sort', e.target.value)} aria-label="Sort books"><option value="title">Title A–Z</option><option value="-title">Title Z–A</option><option value="-year">Newest first</option><option value="year">Oldest first</option></select></div></div>
  {error ? <State kind="error">{error}</State> : !result ? <State>Loading the collection…</State> : result.books.length === 0 ? <State kind="empty"><strong>No books found</strong><br/>Try a different title or remove a filter.</State> : <div className="book-grid">{result.books.map(book => <BookCard key={book._id} book={book}/>)}</div>}
  </main>;
}
function BookDetails() {
  const { id } = useParams(); const [data, setData] = React.useState(null); const [error, setError] = React.useState(''); const [borrowState, setBorrowState] = React.useState('');
  React.useEffect(() => { loadBook(id).then(setData).catch(e => setError(e.response?.data?.message || 'Could not load this book.')); }, [id]);
  async function borrow() { setBorrowState('Sending request…'); try { await api.post(`/borrow/${id}`); setBorrowState('Borrow request submitted.'); const fresh = await loadBook(id); setData(fresh); } catch (e) { setBorrowState(e.response?.data?.message || 'Unable to borrow this book right now.'); } }
  async function reserve() { setBorrowState('Joining the reservation queue…'); try { const r = await api.post(`/reservations/${id}`); setBorrowState(`Reservation placed at position ${r.data.data.reservation.position}.`); } catch (e) { setBorrowState(e.response?.data?.message || 'Unable to reserve this book right now.'); } }
  if (error) return <main className="page"><State kind="error">{error}</State></main>; if (!data) return <main className="page"><State>Loading book details…</State></main>;
  const { book, relatedBooks } = data; const available = book.availableCopies > 0;
  return <main className="page detail-page"><div className="breadcrumb"><Link to="/books">CATALOGUE</Link> <span>/</span> BOOK DETAILS</div><section className="detail-layout"><div className="detail-cover">{book.coverImage ? <img src={book.coverImage} alt={`Cover of ${book.title}`}/> : <div className="cover-placeholder large"><span>LIBRARY<br/>EDITION</span><strong>{book.title}</strong><small>{book.authors?.[0]}</small></div>}</div><div className="detail-copy"><div className="eyebrow">{book.category}</div><h1>{book.title}</h1><p className="detail-author">By {book.authors?.join(', ')}</p><Status available={available}/><p className="description">{book.description || 'A title in the LibraMind university collection.'}</p><div className="availability-box"><div><span className="eyebrow">COPIES AVAILABLE</span><strong>{book.availableCopies} <small>/ {book.totalCopies}</small></strong></div><div className="divider"/><div><span className="eyebrow">SHELF LOCATION</span><strong>{book.shelfLocation || 'Ask library staff'}</strong></div></div><button className="primary-button" disabled={!available} onClick={borrow}>{available ? 'Borrow this book' : 'Currently unavailable'} <span>→</span></button>{!available && <button className="reserve-button" onClick={reserve}>Reserve this book <span>→</span></button>}<div className="borrow-message" aria-live="polite">{borrowState}</div><div className="book-facts">{book.publisher && <span><small>PUBLISHER</small>{book.publisher}</span>}{book.publicationYear && <span><small>YEAR</small>{book.publicationYear}</span>}<span><small>ISBN</small>{book.isbn}</span></div></div></section>
  {relatedBooks.length > 0 && <section className="related"><div className="section-head"><div><div className="eyebrow">KEEP EXPLORING</div><h2>Related books</h2></div><Link to={`/books?category=${encodeURIComponent(book.category)}`}>View all →</Link></div><div className="book-grid related-grid">{relatedBooks.map(b => <BookCard key={b._id} book={b}/>)}</div></section>}</main>;
}
function AdminBooks() {
  const [books, setBooks] = React.useState([]); const [message, setMessage] = React.useState(''); const [busy, setBusy] = React.useState(false);
  const [editing, setEditing] = React.useState(null); const formRef = React.useRef(null);
  async function refresh() { try { setBooks((await loadBooks({ limit: 100, sort: 'title' })).books); } catch (e) { setMessage(e.response?.data?.message || 'Sign in as an admin to manage books.'); } }
  React.useEffect(() => { refresh(); }, []);
  async function submit(e) { e.preventDefault(); const form = e.currentTarget; setBusy(true); setMessage(''); const f = new FormData(form); const body = Object.fromEntries(f); body.authors=body.authors.split(',').map(x=>x.trim()).filter(Boolean); body.tags=body.tags.split(',').map(x=>x.trim()).filter(Boolean); for (const k of ['publicationYear','totalCopies','availableCopies']) body[k] = body[k] ? Number(body[k]) : undefined; try { if (editing) { await api.patch(`/books/${editing._id}`, body); setMessage('Book updated.'); setEditing(null); } else { await api.post('/books', body); setMessage('Book added to the catalogue.'); } form.reset(); await refresh(); } catch (err) { setMessage(err.response?.data?.message || 'Unable to save book.'); } finally { setBusy(false); } }
  function editBook(book) { setEditing(book); const form = formRef.current; for (const [key, value] of Object.entries({ ...book, authors: book.authors.join(', '), tags: book.tags.join(', ') })) { if (form.elements[key]) form.elements[key].value = Array.isArray(value) ? value.join(', ') : value ?? ''; } window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function remove(id) { try { await api.delete(`/books/${id}`); setMessage('Book removed.'); await refresh(); } catch (e) { setMessage(e.response?.data?.message || 'Unable to delete book.'); } }
  return <main className="page admin-page"><div className="breadcrumb">LIBRARY TOOLS <span>/</span> BOOK MANAGEMENT</div><div className="catalogue-heading"><div><div className="eyebrow">ADMINISTRATION</div><h1>Manage books</h1><p>Add titles and keep the collection up to date.</p></div><span className="admin-tag">ADMIN ACCESS</span></div><div className="admin-layout"><form ref={formRef} className="admin-form" onSubmit={submit}><h2>{editing ? 'Edit title' : 'Add a title'}</h2><label>Title<input name="title" required/></label><label>Authors <small>Separate names with commas</small><input name="authors" required/></label><label>ISBN<input name="isbn" required/></label><label>Description<textarea name="description" rows="4"/></label><div className="form-row"><label>Category<input name="category" required/></label><label>Publication year<input name="publicationYear" type="number"/></label></div><div className="form-row"><label>Total copies<input name="totalCopies" type="number" min="0" defaultValue="1" required/></label><label>Available copies<input name="availableCopies" type="number" min="0" defaultValue="1" required/></label></div><div className="form-row"><label>Shelf location<input name="shelfLocation"/></label><label>Publisher<input name="publisher"/></label></div><label>Tags <small>Comma separated</small><input name="tags"/></label><label>Cover image URL<input name="coverImage" type="url"/></label><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Add to catalogue'} <span>→</span></button>{editing && <button type="button" className="cancel-edit" onClick={() => { setEditing(null); formRef.current.reset(); }}>Cancel edit</button>}{message && <p className="form-message">{message}</p>}</form><section className="admin-list"><div className="section-head"><div><div className="eyebrow">COLLECTION</div><h2>All titles <span>{books.length}</span></h2></div></div>{books.length ? books.map(b => <div className="admin-book" key={b._id}><div><strong>{b.title}</strong><span>{b.authors?.join(', ')} · {b.availableCopies}/{b.totalCopies} available</span></div><div className="admin-actions"><button onClick={() => editBook(b)} aria-label={`Edit ${b.title}`}>Edit</button><button onClick={() => remove(b._id)} aria-label={`Delete ${b.title}`}>Delete</button></div></div>) : <State kind="empty">No catalogue records loaded.</State>}</section></div></main>;
}
function Guard({ children, role }) { return <ProtectedRoute role={role}>{children}</ProtectedRoute>; }
function App() { return <AuthProvider><Header/><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/register" element={<RegisterPage/>}/><Route path="/profile" element={<Guard><ProfilePage/></Guard>}/><Route path="/books" element={<Guard><Catalogue/></Guard>}/><Route path="/books/:id" element={<Guard><BookDetails/></Guard>}/><Route path="/my-library" element={<Guard><MyLibrary/></Guard>}/><Route path="/reservations" element={<Guard><Reservations/></Guard>}/><Route path="/fines" element={<Guard><Fines/></Guard>}/><Route path="/admin/books" element={<Guard role="ADMIN"><AdminBooks/></Guard>}/><Route path="*" element={<Guard><Catalogue/></Guard>}/></Routes><footer><span>© LIBRAMIND · UNIVERSITY LIBRARY</span><span>DISCOVER KNOWLEDGE, ONE BOOK AT A TIME</span></footer></AuthProvider>; }

createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);